"""added patronym field in user

Revision ID: 56effe46f22c
Revises: d59c4eab8e4a
Create Date: 2025-07-17 16:06:47.144552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56effe46f22c'
down_revision: Union[str, Sequence[str], None] = 'd59c4eab8e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('patronym', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'patronym')
    # ### end Alembic commands ###
