"""delete status

Revision ID: 7d3492472ab6
Revises: 5e422bf57cbd
Create Date: 2025-07-21 23:46:50.424089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d3492472ab6'
down_revision: Union[str, Sequence[str], None] = '5e422bf57cbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
