"""add Media table

Revision ID: bef1e454e163
Revises: 2a8457478d8a
Create Date: 2025-07-22 00:31:44.733815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bef1e454e163'
down_revision: Union[str, Sequence[str], None] = '2a8457478d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.String(length=200), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('filename', sa.String(length=200), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.Enum('telegram', 'local', 'url', name='sourcetypeenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media')
    # ### end Alembic commands ###
